### PR TITLE
Updated tracking to provide the correct json data to spoor.ingest

### PR DESCRIPTION
**Pull request by adambraimbridge**
Should resolve https://github.com/Financial-Times/next-barriers/issues/30

(Please excuse the linting noise.)

### CODE REVIEW

**Comment by adambraimbridge** [comment]
cc @commuterjoy, @tom-parker, @ifyio

**Comment by commuterjoy** [comment]
@tom-parker are these are the events we banned from keen ?

**Comment by tom-parker** [comment]
@adambraimbridge @commuterjoy ah yep, see https://github.com/Financial-Times/spoor-consumer/blob/master/sinks/keen.js#L103

The ordering of the middleware has been done now so event volumes should be less but did we decide whether we needed to keep them in keen or not?

**Comment by adambraimbridge** [comment]
I'll close this, as my "fix" doesn't actually address it problem.

**Pull request closed without merging**
